### DISCUSSION TITLE
Error while dialing dial tcp 0.0.0.0:50051: connect: connection refused

### DISCUSSION THREAD

**Discussion by bcowell** [anycable/anycable#147] [Q&A] [answered]
### What did you do?
Running docker over WSL. I have a local dev environment using docker-compose to setup anycable-go, anycable-rails, redis and postgres. I'm trying to just subscribe to a channel when everything is running and logs say connection to rpc/redis is fine.

I'm able to hit `http://localhost:8080/cable` directly in the browser,  it just returns `Bad Request`
My console spits out `action_cable.js:241 WebSocket connection to 'ws://localhost:8080/cable' failed: `
And then anycable-go doesn't want to connect to the rpc. I get `Error while dialing dial tcp 0.0.0.0:50051: connect: connection refused` from the anycable-go logs.

I've tried disabling firewall/have all ports open, but it makes no difference.

anycable-go log
```
D 2022-04-27T20:41:38.988Z context=main 🔧 🔧 🔧 Debug mode is on 🔧 🔧 🔧
I 2022-04-27T20:41:38.988Z context=main Starting AnyCable 1.2.0-a9c7945 (pid: 1, open file limit: 1048576)
D 2022-04-27T20:41:38.988Z context=disconnector Calls rate: 10ms         
I 2022-04-27T20:41:38.988Z context=main Handle WebSocket connections at http://0.0.0.0:8080/cable
I 2022-04-27T20:41:38.988Z context=main Handle health connections at http://0.0.0.0:8080/health
D 2022-04-27T20:41:38.988Z context=main Go pools initialized (broadcast: 16)
D 2022-04-27T20:41:38.988Z context=http Starting WebSocket server at http://0.0.0.0:8080
D 2022-04-27T20:41:38.988Z context=metrics No metrics writers. Disable metrics rotation
I 2022-04-27T20:41:38.988Z context=rpc RPC controller initialized: 0.0.0.0:50051 (concurrency: 28, enable_tls: false, proto_versions: v1)
I 2022-04-27T20:41:38.990Z context=pubsub Subscribed to Redis channel: __anycable__

D 2022-04-27T20:42:35.409Z sid=UmmOlHIl1ICFTwlo9ZN2L WebSocket session established
W 2022-04-27T20:42:35.409Z context=rpc Connection is lost. Trying to reconnect immediately
D 2022-04-27T20:42:35.409Z code=Unavailable context=rpc sid=UmmOlHIl1ICFTwlo9ZN2L RPC failure: last connection error: connection error: desc = "transport: Error while dialing dial tcp 0.0.0.0:50051: connect: connection refused"
E 2022-04-27T20:42:35.510Z sid=UmmOlHIl1ICFTwlo9ZN2L WebSocket session failed: grpc connection is not ready
```

anycable-rails log
```
Starting AnyCable RPC server (pid: 1)
AnyCable version: 1.2.3 (proto_version: v1)
Serving Rails application from ./config/environment.rb
gRPC version: 1.45.0
Broadcasting Redis channel: __anycable__
RPC server is starting...
RPC server is listening on 0.0.0.0:50051 (workers_num: 30)
```

docker-compose
```
version: "3.9"

services:

  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /run/postgresql:/run/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    hostname: redis
    ports:
      - 6379:6379

  sidekiq:
    depends_on:
      - postgres
      - redis
    build: .
    environment:
      - REDIS_URL=redis://redis
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app

  rpc:
    build: .
    command: bundle exec anycable
    environment:
      - ANYCABLE_RPC_HOST=0.0.0.0:50051
    ports:
      - 50051:50051

  anycable:
    image: anycable/anycable-go:latest
    depends_on:
      - redis
      - rpc
    environment:
      - ANYCABLE_HOST=0.0.0.0
      - ANYCABLE_PORT=8080
      - ANYCABLE_RPC_HOST=0.0.0.0:50051
      - REDIS_URL=redis://redis
      - ANYCABLE_DEBUG=1
    ports:
      - 8080:8080

volumes:
  redis:
  pgdata:
```

Dockerfile is just the default ruby one for 3.0.2

anycable.yml
```
  access_logs_disabled: false
  rpc_host: "127.0.0.1:50051"
  log_grpc: false
  broadcast_adapter: redis
  redis_channel: "__anycable__"
```

I've tried a bunch of variations of 0.0.0.0, localhost, 127.0.0.1 and using the rpc docker container ip directly with no luck.
Any input or advice would be really appreciated

**Comment by Envek** [comment, marked as answer]
You should specify `ANYCABLE_RPC_HOST` to point to docker hostname of AnyCable RPC container (`rpc` in your case). Then it should work:

```yml
  anycable:
    image: anycable/anycable-go:latest
    environment:
      - ANYCABLE_RPC_HOST=rpc:50051
```
