### DISCUSSION TITLE
How to setup AnyCable with Docker

### DISCUSSION THREAD

**Discussion by El-Potato-Slayer** [anycable/anycable#149] [Q&A] [answered]
Hi there!

I'm quite new to Docker and I've been trying to create an image that includes AnyCable. But the resources I found regarding Dockerizing AnyCable aren't very beginner-friendly.

I ran the anycable:setup command and it gave me a snippet, and I modified it accordingly (which may be wrong).
I modified the snippet. I'm not 100% sure what's essential. The web service and database work without an issue, but I'm not able to connect to the WebSocket. Without Docker (just running the app locally), I can connect with the front-end. But with Docker, I only receive the broadcasts that a channel disconnected.

When looking at the logs, I see this:
```
backend-anycable-1  | [AnyCable sid=iZYTRVu_oQFjZGTLibPYL] Started "/cable" [AnyCable] for 172.18.0.1 at 2022-05-16 02:16:39 +0000
backend-anycable-1  | connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
backend-anycable-1  |         Is the server running on that host and accepting TCP/IP connections?
backend-ws-1        | D 2022-05-16T02:16:39.824Z context=rpc sid=iZYTRVu_oQFjZGTLibPYL Authenticate response: error_msg:"connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (::1), port 5432 failed: Address not available\n\tIs the server running on that host and accepting TCP/IP connections?\n"
backend-anycable-1  | connection to server at "localhost" (::1), port 5432 failed: Address not available
```

From what I understand, that's the port of the database. But I can't find any issues with it.
Does anyone know how to solve this issue?

Here's my Dockerfile
```
FROM ruby:3.1.2-alpine

RUN apk add --no-cache --update build-base \
                                bash \
                                linux-headers \
                                postgresql-dev \
                                tzdata \
                                git \
                                nodejs \
                                yarn \
                                sudo \
                                libc6-compat
RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

RUN gem install --platform ruby google-protobuf -v '3.20.1' -N
RUN gem install --platform ruby grpc -v '1.38.0' -N --ignore-dependencies && \
    rm -rf /usr/local/bundle/gems/grpc-1.38.0/src/ruby/ext

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler
RUN bundle install --no-binstubs --jobs $(nproc) --retry 5

COPY . .

CMD ["anycable"]
```

Here's my docker-compose file
```
version: '3.8'

services:
  db:
    image: 'postgres:14.2-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  ws:
    image: anycable/anycable-go:1.2
    ports:
      - '8080:8080'
    environment:
      ANYCABLE_HOST: "0.0.0.0"
      ANYCABLE_REDIS_URL: redis://redis:6379/0
      ANYCABLE_RPC_HOST: anycable:50051
      ANYCABLE_DEBUG: 1
    depends_on:
      redis:
        condition: service_healthy

  web: &backend
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    environment: &backend_environment
      - DATABASE_HOST=db

  anycable:
    <<: *backend
    command: bundle exec anycable
    environment:
      ANYCABLE_REDIS_URL: redis://redis:6379/0
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
      ANYCABLE_DEBUG: 1
    ports:
      - '50051'
    depends_on:
      ws:
        condition: service_started

volumes:
  redis:
  postgres:
```

**Comment by Envek** [comment, marked as answer]
You need to provide database address to `anycable` service too.

Either include `backend_environment` to `anycable` service `environment` (and make sure they use the same hash-style definition) or provide `DATABASE_URL` (or your seemingly custom `DATABASE_HOST`) env var to `anycable` service explicitly.

```yaml
  web: &backend
    environment: &backend_environment
      DATABASE_HOST: db
      ANYCABLE_REDIS_URL: redis://redis:6379/0

  anycable:
    <<: *backend
    environment:
      <<: *backend_environment
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
      ANYCABLE_DEBUG: 1
```

Please note that I also moved `ANYCABLE_REDIS_URL` to `web` as Web processes often also need to know where AnyCable Redis is to send broadcasts from within actions processing web request.
