### DISCUSSION TITLE
RPC not broadcast message

### DISCUSSION THREAD

**Discussion by Khamonluckssa** [anycable/anycable#162] [General]
Hi, i have set up any cable with docker and the message not broadcasting some how, i got this error
```
[2022-09-11 17:49:41.950] ERROR -- NotImplementedError: nil
```
and if i remove ```stream_from "room_channel_#{params[:room_id]}"``` the error is gone and i can connect to channel but it is not received the data

this is room_channel.js
```
import consumer from "./consumer"
document.addEventListener('turbolinks:load', () => {
  console.log("enter room_channel");
  const room_element = document.getElementById('room-id');
  console.log("room_element" + room_element);

  if(room_element){
    const room_id = room_element.getAttribute('data-room-id');
    console.log("room_id" + room_id);

    consumer.subscriptions.subscriptions.forEach((subscription) => {
      console.log("consumer" + consumer);
      console.log("subscription" + subscription);
      consumer.subscriptions.remove(subscription);
    })

    console.log("connect_room_id" + room_id);

    if(room_id){
      console.log("room id is exist_" + room_id);
      consumer.subscriptions.create({channel: "RoomChannel", room_id: room_id}, {
        connected() {
          console.log('connected' + room_id);
        },

        disconnected() {
          // Called when the subscription has been terminated by the server
        },

        received(data) {
          console.log(data);

          const user_element = document.getElementById('chat-user-id');
          const user_id = user_element.getAttribute('data-chat-user-id');

          let html;

          if(user_id === data.user_id){
            html = data.mine
          }else{
            html = data.theris
          }

          const messageContainer = document.querySelector("#messages:last-child")
          messageContainer.innerHTML = messageContainer.innerHTML + html

          //reset text box
          
          var text_box = document.getElementById('message_content');
          text_box.value = "";
          // Called when there's incoming data on the websocket for this channel
        }
      });
    }
  
  }
 

})
```

my room_channel.rb
```
class RoomChannel < ApplicationCable::Channel
  state_attr_accessor :room

  def subscribed
    stream_from "room_channel_#{params[:room_id]}"
  end

  def unsubscribed
    Rails.logger.info("---unsubscribed ---")
  end
end
```

this is docker-compose
```
version: "3"

volumes:
  data-uploads:
  packs:
services:
  app:
    build:
      context: .
      dockerfile: ./dockers/app/Dockerfile
    container_name: comp_moto_app
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/public/assets
      - /app/public/packs
    depends_on:
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis@redis:6379/0
  db:
    image: "postgres:14.1-alpine"
    container_name: comp_moto_db
    environment:
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
      POSTGRES_DB: ${DOCKER_DB_NAME}
    volumes:
      - /docker_data/comp_moto_app/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    build:
      context: .
      dockerfile: ./dockers/web/Dockerfile
    container_name: comp_moto_web
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./dockers/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  redis:
    image: redis:6.2.6-alpine
    container_name: comp_moto_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - /docker_data/comp_moto/production/redis:/data
      - ./dockers/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  delayed_job:
    build:
      context: .
      dockerfile: ./dockers/delayed_job/Dockerfile
    container_name: comp_moto_delayed_job
    command: bundle exec rails jobs:work
    depends_on:
      - db
    volumes:
      - .:/app    
  anycable:
    build:
      context: .
      dockerfile: ./dockers/cable/Dockerfile
    container_name: comp_moto_anycable
    command: bundle exec anycable 
    environment:
      ANYCABLE_REDIS_URL: redis://redis@redis:6379/0
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
      ANYCABLE_DEBUG: 1
    ports:
      - '50051:50051'
    depends_on:
      - redis
      - db
  ws: 
    image:  anycable/anycable-go:latest-alpine
    command: anycable-go 
    container_name: comp_moto_ws
    ports:
      - '8080:8080'
    environment: 
      ANYCABLE_HOST: "0.0.0.0"
      ANYCABLE_PORT: 8080
      ANYCABLE_REDIS_URL: redis://redis@redis:6379/0
      ANYCABLE_RPC_HOST: anycable:50051
      ANYCABLE_DEBUG: 1
    depends_on:
      - redis
      - anycable
  sidekiq:
    build:
      context: .
      dockerfile: ./dockers/sidekiq/Dockerfile
    container_name: comp_moto_sidekiq
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
       - data-uploads:/app/public/uploads
```
       
 this is log for anycable-go container, is it running?

```
D 2022-09-11T17:49:31.753Z context=main 🔧 🔧 🔧 Debug mode is on 🔧 🔧 🔧
I 2022-09-11T17:49:31.753Z context=main Starting AnyCable 1.2.2-4ef479c (pid: 1, open file limit: 1048576, gomaxprocs: 4)
D 2022-09-11T17:49:31.753Z context=disconnector Calls rate: 10ms         
I 2022-09-11T17:49:31.756Z context=rpc RPC controller initialized: anycable:50051 (concurrency: 28, enable_tls: false, proto_versions: v1)
I 2022-09-11T17:49:31.756Z context=main Handle WebSocket connections at http://0.0.0.0:8080/cable
I 2022-09-11T17:49:31.756Z context=main Handle health connections at http://0.0.0.0:8080/health
D 2022-09-11T17:49:31.756Z context=main Go pools initialized (broadcast: 16)
D 2022-09-11T17:49:31.756Z context=http Starting WebSocket server at http://0.0.0.0:8080
D 2022-09-11T17:49:31.756Z context=metrics No metrics writers. Disable metrics rotation
I 2022-09-11T17:49:31.850Z context=pubsub Subscribed to Redis channel: __anycable__
```

this is log for anycable (normally when the message broadcast message, it should called RPC Connect right? because on my local it show log  RPC Connect but on production this log is nothing like below)

```
Starting AnyCable RPC server (pid: 1)
AnyCable version: 1.2.3 (proto_version: v1)
Serving Rails application from ./config/environment.rb
gRPC version: 1.48.0
handling /anycable.RPC/Connect with #<Method: AnyCable::GRPC::Handler#connect(request, call) /usr/local/bundle/gems/anycable-core-1.2.3/lib/anycable/grpc/handler.rb:12>
handling /anycable.RPC/Command with #<Method: AnyCable::GRPC::Handler#command(request, call) /usr/local/bundle/gems/anycable-core-1.2.3/lib/anycable/grpc/handler.rb:20>
handling /anycable.RPC/Disconnect with #<Method: AnyCable::GRPC::Handler#disconnect(request, call) /usr/local/bundle/gems/anycable-core-1.2.3/lib/anycable/grpc/handler.rb:16>
handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::Checker#check(req, _call) /usr/local/bundle/gems/grpc-1.48.0-x86_64-linux/src/ruby/pb/grpc/health/checker.rb:34>
handling /grpc.health.v1.Health/Watch with #<Method: Grpc::Health::Checker(Grpc::Health::V1::Health::Service)#watch(*) /usr/local/bundle/gems/grpc-1.48.0-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:99>
Broadcasting Redis channel: __anycable__
RPC server is starting...
RPC server is listening on 0.0.0.0:50051 (workers_num: 30)
```

**Comment by palkan** [comment]
Hey!
Can you share your `cable.yml`, please? Does it have `adapter` set to `any_cable`?

**Reply by Khamonluckssa** [reply]
@palkan 
```
development:
  adapter: any_cable

test:
  adapter: test

production:
  adapter: any_cable
```
this is cable.yml

**Reply by Khamonluckssa** [reply]
Can you help me please? @palkan

**Reply by palkan** [reply]
Let's try to debug the exception by using the following snippet in the channel class:

```ruby
def subscribed
    stream_from "room_channel_#{params[:room_id]}"
rescue Exception => e
   puts e.backtace.take(20).join("\n")
   raise
end
```

That should show us more information about the source of the exception.

**Reply by dmgrinko1** [reply]
@palkan Hi, can you help me please? Should I open another question? I`m trying to migrate from action to any cable. But I have completely same issue. IOS + Rails API
Here is my subscribe method

    def subscribed
       stream_for non_session_user
       return unless non_session_user
       update_user_status(:online)
       send_initial_data
    end

  exception shows nothing in this case.
   But it comes from here action_cable/subscription_adapter/base.rb #subscribe

**Reply by dmgrinko1** [reply]
@Khamonluckssa hi, have you fixed your issue?

**Reply by palkan** [reply]
Hey @dmgrinko1 !

Could you please show the full backtrace from the logs?

> But it comes from here action_cable/subscription_adapter/base.rb #subscribe

What is the value of `adapter` in your `cable.yml`?
Or, do you set `ActionCable.server.config.cable = <whatever>` anywhere?

Also, what is the value of `ActionCable.server.pubsub`?

**Reply by dmgrinko1** [reply]
Hi @palkan thank you for quick responce  
ruby '3.1.2'
gem 'rails', '~> 6.1', '>= 6.1.6.1'

 cable.yml
 ```
    development:
      adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
      channel_prefix: 5andgo_development
    test:
       adapter: test
    production:
       adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %> 
       channel_prefix: 5andgo_production
```
development.rb
```
  config.after_initialize do
    if AnyCable::Rails.enabled?
       config.action_cable.url = ActionCable.server.config.url = ENV.fetch('CABLE_URL', 'ws://localhost:8080/cable')
    end
  end
```
ActionCable.server.pubsub
```
    #<ActionCable::SubscriptionAdapter::AnyCable:0x00000001107a51f0>
```

anycable.yml
```
default: &default
  access_logs_disabled: false
  rpc_host: "127.0.0.1:50051"
  log_grpc: false
  broadcast_adapter: redis
  redis_channel: "__anycable__"

development:
  <<: *default
  redis_url: redis://localhost:6379/3
test:
  <<: *default
production:
  <<: *default
  redis_url: redis://redis-service:6379/3
```

bundle exec anycable
```
Starting AnyCable RPC server (pid: 48512)
AnyCable version: 1.2.3 (proto_version: v1)
Serving Rails application from ./config/environment.rb
gRPC version: 1.49.1
Broadcasting Redis channel: __anycable__
RPC server is starting...
RPC server is listening on 127.0.0.1:50051 (workers_num: 30)
```

anycable-go --port=8080
```
INFO 2022-10-12T05:06:10.848Z context=main Starting AnyCable 1.2.1 (pid: 48762, open file limit: 10240, gomaxprocs: 8)
  INFO 2022-10-12T05:06:10.849Z context=rpc RPC controller initialized: localhost:50051 (concurrency: 28, enable_tls: false, proto_versions: v1)
  INFO 2022-10-12T05:06:10.849Z context=main Handle WebSocket connections at http://localhost:8080/cable
  INFO 2022-10-12T05:06:10.849Z context=main Handle health connections at http://localhost:8080/health
  INFO 2022-10-12T05:06:10.855Z context=pubsub Subscribed to Redis channel: __anycable__
  ```
log
```
Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2022-10-12 09:01:35 +0400
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
[2022-10-12 05:01:35 UTC] Websocket event occured: #<struct WebSocket::Driver::OpenEvent>
source=rack-timeout id=17e8f0f8-c30b-4785-95ff-adfb687c818c timeout=15000ms service=463ms state=completed
Registered connection (BQoar_K25GOVqSF6zWDYHQ)
[2022-10-12 09:01:35.988] ERROR -- NotImplementedError: nil
[2022-10-12 05:01:38 UTC] Websocket beat transmitted
[2022-10-12 05:01:41 UTC] Websocket beat transmitted
[2022-10-12 05:01:44 UTC] Websocket beat transmitted
[2022-10-12 05:01:45 UTC] Websocket event occured: #<struct WebSocket::Driver::MessageEvent data="{\"command\":\"subscribe\",\"identifier\":\"{\\\"channel\\\":\\\"NotificationChannel\\\"}\"}">
[2022-10-12 09:01:45.838] ERROR -- NotImplementedError: nil
[2022-10-12 05:01:47 UTC] Websocket beat transmitted
```
and on close event 
```
[2022-10-12 05:07:15 UTC] Websocket beat transmitted
[2022-10-12 05:07:17 UTC] Websocket close occured: reason - , code - 1000
[2022-10-12 05:07:17 UTC] Websocket event occured: #<struct WebSocket::Driver::CloseEvent code=1000, reason="">
Finished "/cable/" [WebSocket] for 127.0.0.1 at 2022-10-12 09:07:17 +0400
There was an exception - NotImplementedError(NotImplementedError)
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/subscription_adapter/base.rb:25:in `unsubscribe'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/channel/streams.rb:122:in `block in stop_all_streams'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/channel/streams.rb:121:in `each'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/channel/streams.rb:121:in `stop_all_streams'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/anycable-rails-1.3.4/lib/anycable/rails/action_cable_ext/channel.rb:38:in `stop_all_streams'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:270:in `block in simple'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `block in invoke_after'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `each'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `invoke_after'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:131:in `block in run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-rails-5.4.2/lib/sentry/rails/action_cable.rb:21:in `block in capture'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-ruby-5.4.2/lib/sentry/hub.rb:59:in `with_scope'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-ruby-5.4.2/lib/sentry-ruby.rb:352:in `with_scope'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-rails-5.4.2/lib/sentry/rails/action_cable.rb:13:in `capture'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-rails-5.4.2/lib/sentry/rails/action_cable.rb:78:in `sentry_capture'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-rails-5.4.2/lib/sentry/rails/action_cable.rb:69:in `block (2 levels) in included'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/execution_wrapper.rb:87:in `wrap'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/engine.rb:68:in `block (3 levels) in <class:Engine>'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/anycable-rails-1.3.4/lib/anycable/rails/compatibility.rb:31:in `block in run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/anycable-rails-1.3.4/lib/anycable/rails/compatibility.rb:38:in `__anycable_check_ivars__'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/anycable-rails-1.3.4/lib/anycable/rails/compatibility.rb:31:in `run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/channel/base.rb:191:in `unsubscribe_from_channel'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/connection/subscriptions.rb:51:in `remove_subscription'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/connection/subscriptions.rb:64:in `block in unsubscribe_from_all'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/connection/subscriptions.rb:64:in `each'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/connection/subscriptions.rb:64:in `unsubscribe_from_all'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/connection/base.rb:188:in `handle_close'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-rails-5.4.2/lib/sentry/rails/action_cable.rb:59:in `block in handle_close'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-rails-5.4.2/lib/sentry/rails/action_cable.rb:21:in `block in capture'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-ruby-5.4.2/lib/sentry/hub.rb:59:in `with_scope'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-ruby-5.4.2/lib/sentry-ruby.rb:352:in `with_scope'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-rails-5.4.2/lib/sentry/rails/action_cable.rb:13:in `capture'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/sentry-rails-5.4.2/lib/sentry/rails/action_cable.rb:58:in `handle_close'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/server/worker.rb:60:in `block in invoke'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/server/worker.rb:42:in `block in work'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `block in with_database_connections'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `block in tag'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `tag'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `with_database_connections'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/engine.rb:62:in `block (4 levels) in <class:Engine>'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/engine.rb:57:in `block (3 levels) in <class:Engine>'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/server/worker.rb:41:in `work'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/server/worker.rb:59:in `invoke'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/actioncable-6.1.7/lib/action_cable/server/worker.rb:54:in `block in async_invoke'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/Users/admin/.rvm/gems/ruby-3.1.2@fiveandgo/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```
Looking at logs I`ve added marker here. 'anycable/rails/action_cable_ext/channel.rb' AndI see  that 'anycabled?' method returns false, 
Maybe here the problem
```
def anycabled?
     connection.instance_variable_defined?(:@anycable_socket)
    # Use instance variable check here for testing compatibility
    connection.instance_variable_defined?(:@anycable_socket)
end
```
other methods here using super unless anycabled?
seems thats why it raises NotEmplementedError from here (base class(
/gems/actioncable-6.1.7/lib/action_cable/subscription_adapter/base.rb:25:in `unsubscribe' or 
/gems/actioncable-6.1.7/lib/action_cable/subscription_adapter/base.rb:25:in `subscribe'
Also I have a doubt about 'stream_for' method that I showed above, maybe it does not support? But I saw it your example PR
https://github.com/anycable/anycable_rails_demo/pull/2/files
