### DISCUSSION TITLE
Anycable RPC-less setup on Kubernetes problem

### DISCUSSION THREAD

**Discussion by selivandex** [anycable/anycable#169] [General]
Hello,

I have a problem with production rpc-less deploy on k8s. When pod with anycable-go starts it trying to connect to RPC server which doesn't exists and getting error:

```
D 2022-11-11T03:22:27.242Z context=ws Websocket session initialization failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused"
```

My values.yml

```
anycable-go:
  replicas: 1
  name: anycable-go
  env:
    anycableRedisUrl: redis://192.168.0.11:6379/7
    anycablePort: 8080
    anycableHeaders: cookie,origin
    anycableLogLevel: debug
    anycableLogFormat: json
    anycableDebug: true
    anycableDisableDisconnect: true
    anycableJwtIdKey: secret
    anycableTurboRailsKey: secret
  ingress:
    enable: true
    path: /cable
    host: ws.example.com
    acme:
      hosts:
        - ws.example.com
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      cert-manager.io/issue-temporary-certificate: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 2048m
      nginx.ingress.kubernetes.io/websocket-services: "anycable-go"
      kubernetes.io/ingress.class: nginx
  tls:
    secretName: anycable-go-tls
```

What am i doing wrong? How to start anycable-go without RPC server?
