### DISCUSSION TITLE
terminate called after throwing an instance of 'std::logic_error'

### DISCUSSION THREAD

**Discussion by vitaliiorlov** [anycable/anycable#220] [General]
Hi!
I would like to discuss what I'm doing wrong, so I wanted to start anycable server in docker. But got error when anycable container starting:

```
2023-11-03 18:29:13 Anyway Config was loaded before Rails. Activating Anyway Config Rails plugins now.
2023-11-03 18:29:13 NOTE: Already loaded configs were provisioned without Rails-specific sources.
2023-11-03 18:29:13 
2023-11-03 18:29:13 ⛔️ WARNING: AnyCable RPC pool size (30) is greater than DB pool size (5)
2023-11-03 18:29:13 Please, consider adjusting the database pool size to avoid connection wait times and increase throughput of your RPC server
2023-11-03 18:29:13 
2023-11-03 18:29:13 Starting AnyCable RPC server (pid: 1)
2023-11-03 18:29:13 AnyCable version: 1.4.3 (proto_version: v1)
2023-11-03 18:29:13 Serving Rails application from ./config/environment.rb
# remember this log :) => 2023-11-03 18:29:13 +++
2023-11-03 18:29:13 gRPC version: 1.59.2
2023-11-03 18:29:13 terminate called after throwing an instance of 'std::logic_error'
2023-11-03 18:29:13   what():  basic_string::_S_construct null not valid
```

### Setup logs:
```
docker-compose run --rm app bundle install
[+] Building 0.0s (0/0)                                                                                                   docker:default
[+] Creating 3/0
 ✔ Container db_container           Running                                                                                         0.0s 
 ✔ Container redis_container        Running                                                                                         0.0s 
 ✔ Container mailcatcher_container  Running                                                                                         0.0s 
[+] Building 0.0s (0/0)                                                                                                   docker:default
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching google-protobuf 3.25.0 (x86_64-linux)
Fetching anyway_config 2.5.4
Installing anyway_config 2.5.4
Installing google-protobuf 3.25.0 (x86_64-linux)
Fetching anycable-core 1.4.3
Fetching googleapis-common-protos-types 1.9.0
Installing anycable-core 1.4.3
Fetching anycable-rails-core 1.4.2
Installing googleapis-common-protos-types 1.9.0
Fetching grpc 1.59.2 (x86_64-linux)
Installing anycable-rails-core 1.4.2
Installing grpc 1.59.2 (x86_64-linux)
Fetching anycable 1.4.3
Installing anycable 1.4.3
Fetching anycable-rails 1.4.2
Installing anycable-rails 1.4.2
Bundle complete! 59 Gemfile dependencies, 183 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
╭─vitaliiorlov@Vitalii-PC ~/pj/api
╰─➤  docker-compose exec app bundle exec rails g anycable:setup

👋 Welcome to AnyCable interactive installer.
    conflict  config/cable.yml
Overwrite /api/config/cable.yml? (enter "h" for help) [Ynaqdhm] Y
       force  config/cable.yml
      create  config/anycable.yml
        info  ✅ 'config.action_cable.url' has been configured
        help  ⚠️  If you're using JS client make sure you have `action_cable_meta_tag` included before any <script> tag in your application.html
Which environment do you use for development? (1) Local, (2) Docker, (0) Skip 2
        gsub  config/anycable.yml
        help  ️️⚠️  Docker development configuration could vary
Here is an example snippet for docker-compose.yml:
─────────────────────────────────────────
ws:
  image: anycable/anycable-go:1.4
  ports:
    - '8080:8080'
  environment:
    ANYCABLE_HOST: "0.0.0.0"
    ANYCABLE_REDIS_URL: redis://redis:6379/0
    ANYCABLE_RPC_HOST: anycable:50051
    ANYCABLE_DEBUG: 1
  depends_on:
    redis:
      condition: service_healthy

anycable:
  <<: *backend
  command: bundle exec anycable
  environment:
    <<: *backend_environment
    ANYCABLE_REDIS_URL: redis://redis:6379/0
    ANYCABLE_RPC_HOST: 0.0.0.0:50051
    ANYCABLE_DEBUG: 1
  ports:
    - '50051'
  depends_on:
    <<: *backend_depends_on
    ws:
      condition: service_started
─────────────────────────────────────────
Do you use Heroku for deployment? [Yn] n
      create  config/initializers/anycable.rb
        info  ✅ config/initializers/anycable.rb with Devise configuration has been added
        info  🤖 Running static compatibility checks with RuboCop
         run  bundle exec rubocop -r 'anycable/rails/compatibility/rubocop' --only AnyCable/InstanceVars,AnyCable/PeriodicalTimers,AnyCable/InstanceVars from "."
Inspecting 551 files
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

551 files inspected, no offenses detected
Do you want to use JWT for authentication? [Yn] n
        info  ✅ AnyCable has been configured successfully!
```

## docker-compose.yml
```
...
ws:
    image: anycable/anycable-go:latest
    ports:
      - '8080:8080'
    environment:
      ANYCABLE_HOST: "0.0.0.0"
      ANYCABLE_REDIS_URL: redis://redis:6379/0
      ANYCABLE_RPC_HOST: anycable:50051
      ANYCABLE_DEBUG: 1
    env_file:
      - .env.development
    depends_on:
      redis:
        condition: service_healthy

  anycable:
    <<: *backend
    command: bundle exec anycable
    environment:
      ANYCABLE_REDIS_URL: redis://redis:6379/0
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
      ANYCABLE_DEBUG: 1
    env_file:
      - .env.development
    ports:
      - '50051'
    depends_on:
      ws:
        condition: service_started
...
```

### config/anycable.yml
```
# This file contains per-environment settings for AnyCable.
#
# Since AnyCable config is based on anyway_config (https://github.com/palkan/anyway_config), all AnyCable settings
# can be set or overridden through the corresponding environment variables.
# E.g., `rpc_host` is overridden by ANYCABLE_RPC_HOST, `debug` by ANYCABLE_DEBUG etc.
#
# Note that AnyCable recognizes REDIS_URL env variable for Redis pub/sub adapter. If you want to
# use another Redis instance for AnyCable, provide ANYCABLE_REDIS_URL variable.
#
# Read more about AnyCable configuration here: https://docs.anycable.io/ruby/configuration
#
default: &default
  # Turn on/off access logs ("Started..." and "Finished...")
  access_logs_disabled: false
  # Whether to enable gRPC level logging or not
  log_grpc: false
  # Use Redis to broadcast messages to AnyCable server
  broadcast_adapter: redis
  # Use the same channel name for WebSocket server, e.g.:
  #   $ anycable-go --redis_channel="__anycable__"
  redis_channel: "__anycable__"
  # You can use REDIS_URL env var to configure Redis URL.
  # Localhost is used by default.

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

```

### development.rb
```
...
  config.after_initialize do
    if AnyCable::Rails.enabled?
      config.action_cable.url = ActionCable.server.config.url = ENV.fetch("CABLE_URL", "ws://localhost:8080/cable")
    end
  end
```

### config/initializers/anycable.rb
```
# frozen_string_literal: true

# Add Warden middleware to AnyCable stack to allow accessing
# Devise current user via `env["warden"].user`.
#
# See https://docs.anycable.io/ruby/authentication
AnyCable::Rails::Rack.middleware.use(Warden::Manager) do |config|
  Devise.warden_config = config
end
```

### cable.yml
```
# Make it possible to switch adapters by passing the ACTION_CABLE_ADAPTER env variable.
# For example, you can use it fallback to the standard Action Cable in staging/review
# environments (by setting `ACTION_CABLE_ADAPTER=redis`).
development:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

test:
  adapter: test

staging:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
```

### Catching error inside the gem
![image](https://github.com/anycable/anycable/assets/1788994/f9db6024-0823-4a09-b118-2ae3cf5e36ca)

As you can see in the beginning of my message log "+++" exists, but "---" not.
And finally `config.inspect` before crashing =>
```
{
  config_name: "anycable",
  env_prefix: "ANYCABLE",
  values: {
    presets: [],
    broadcast_adapter: "redisx",
    redis_url: "redis://redis:6379/0",
    redis_sentinels: nil,
    redis_channel: "__anycable__",
    redis_tls_verify: false,
    redis_tls_client_cert_path: nil,
    redis_tls_client_key_path: nil,
    nats_servers: ["nats://localhost:4222"],
    nats_channel: "__anycable__",
    nats_dont_randomize_servers: false,
    nats_options: {},
    http_broadcast_url: "http://localhost:8090/_broadcast",
    http_broadcast_secret: nil,
    log_file: nil,
    log_level: "info",
    debug: true,
    http_health_port: nil,
    http_health_path: "/health",
    http_rpc_secret: nil,
    version_check_enabled: true,
    sid_header_enabled: true,
    rpc_host: "0.0.0.0:50051",
    rpc_tls_cert: nil,
    rpc_tls_key: nil,
    rpc_pool_size: 30,
    rpc_max_waiting_requests: 20,
    rpc_poll_period: 1,
    rpc_pool_keep_alive: 0.25,
    rpc_server_args: {},
    rpc_max_connection_age: 300,
    log_grpc: true,
    access_logs_disabled: true,
    persistent_session_enabled: false,
    embedded: false,
    http_rpc_mount_path: nil,
    batch_broadcasts: false,
    socket_id_header: "X-Socket-ID",
    disable_rpc_pool_size_warning: false
  }
}
```

What I am doing wrong?)
Thank you!
