### DISCUSSION TITLE
Running two or more Rails apps using Anycable in the same server

### DISCUSSION THREAD

**Discussion by Roko131** [anycable/anycable#230] [Q&A] [answered]
Hi
So let's say we have `app1.com`, `app2.com` on a single server

So per [docs](https://docs.anycable.io/rails/getting_started?id=configuration) I would need 
```sh
anycable-go --host=localhost --port=8080
bundle exec anycable
```

```yml
# config/anycable.yml
development:
  redis_url: redis://localhost:6379/1
production:
  redis_url: redis://my.redis.io:6379/1
```
So for two apps:
Must I run `anycable-go` command twice? once with each host? I can use the same port right?
Or maybe I need to only run this command once? for both apps?
```sh
# option 1 single process for both apps
anycable-go --host=app1.com,app2.com --port=8080
# option 2 different host same port
anycable-go --host=app1.com --port=8080
anycable-go --host=app2.com --port=8080
# option 3 different host + port
anycable-go --host=app1.com --port=8080
anycable-go --host=app2.com --port=8081
```
Regarding `redis` - can I use the same redis_url?
```yml
# option1 same redis/port, same DB
redis_url: redis://localhost:6379/1 # app1
redis_url: redis://localhost:6379/1 # app2
# option2 same redis/port, different DB
redis_url: redis://localhost:6379/1 # app1
redis_url: redis://localhost:6379/2 # app2
# option3 different redis process, 
redis_url: redis://localhost:6379/1 # app1
redis_url: redis://localhost:6380/1 # app2
```

To summarize:
1. Can I use the same `redis_url` inside `anycable.yml` for both `app1` and `app2`?
2. How should I go about running `anycable-go --host=localhost --port=8080`, Can I achieve it by using a single process call?
