### DISCUSSION TITLE
Anycable and Kamal 2 healthchecks

### DISCUSSION THREAD

**Discussion by pjpires** [anycable/anycable#238] [Q&A]
Hello,

First of all, thanks for the great work - we've been using anycable in production in a rails app for a couple of years now, and it's been a pretty smooth experience. 🙏 

That said, the project's deployment setup is a bit dated, and still relies on capistrano. I'm trying to explore Kamal 2, but I'm struggling with making it work with anycable.

My understanding of [this section of the docs](https://kamal-deploy.org/docs/upgrading/configuration-changes/#healthchecks) is that `kamal-proxy` will perform the healthcheck on all "proxy roles" at the specified path (or the default one, which is `/up` I believe). This turned my attention to anycable for an healthcheck endpoint, and I realized there's a way to setup one. However, it runs as a separate rack server, at a different port from anycable itself. From my testing, I think that invalidates the possibility of using kamal 2, because it doesn't allow me to configure a specific port for the healthcheck, only the path (it will always use the defined `app_port` from the config).

This is the relevant section of my deploy.yml file at the moment:

```yml
# service, image ...

servers:
  web:
    - <%= ENV['HOST'] %>

  anycable-rpc:
    hosts:
      - <%= ENV['WEBSOCKET_HOST'] %>
    cmd: bundle exec anycable
    env:
      clear:
        ANYCABLE_HTTP_HEALTH_PORT: 54321
    proxy:
      hosts:
        - <%= ENV['WEBSOCKET_HOST'] %>
      app_port: 50051
      healthcheck:
        path: /health # <-- problem is here I think, the healtcheck will be attempted at :50051/health

proxy:
  ssl: true
  hosts:
    - <%= ENV['HOST'] %>

# registry stuff, not relevant...

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    DB_HOST: my-app-db
    REDIS_URL: "redis://my-app-redis:6379"
    HOST: <%= ENV['HOST'] %>
    ANYCABLE_RPC_HOST: "0.0.0.0:50051"
    ANYCABLE_REDIS_URL: "redis://my-app-redis:6379/0"
    ANYCABLE_WEBSOCKET_URL: "wss://<%= ENV['WEBSOCKET_HOST'] %>/cable"

accessories:
  db:
    image: postgres:16
    # postgres config...

  redis:
    image: redis:7.0
    # redis config...

  anycable-go:
    image: anycable/anycable-go:1.5
    host: <%= ENV['HOST'] %>
    port: "127.0.0.1:8080:8080"
    env:
      clear:
        ANYCABLE_HOST: "0.0.0.0"
        ANYCABLE_PORT: 8080
        ANYCABLE_RPC_HOST: "my-app-anycable-rpc:50051"
        ANYCABLE_REDIS_URL: "redis://my-app-redis:6379/0"
```

When I try to deploy/boot the servers with this configuration I get this:
```
docker stderr: Error: target failed to become healthy
```

I'm not too familiar with Kamal (or deploying with docker, really), so it might just be a problem in my config. Anyway, I thought I'd post here in case someone is able to help. 

Related: @palkan, I saw that there are a few examples as draft PRs related to deploying with a few different configurations in https://github.com/anycable/anycable_rails_demo, would it be worthy to add one specifically for Kamal 2?

Thanks in advance!

**Comment by palkan** [comment]
Hey!

> it will always use the defined app_port from the config

The thing is that the 50051 is used by gRPC, while the HTTP health server runs on a different port, because it's a separate interface. (For gRPC we have gRPC health checks, but those are not supported by Kamal).

However, I don't think you need to run AnyCable RPC as a server in Kamal's terms; it's more like a worker, a Sidekiq. I'm not sure if Kamal supports health checks for workers though.

Alternatively, you may try specify the health check server port as the `app_port`; you should be still able to expose the gRPC port within the internal Kamal's Docker network.

**Reply by pjpires** [reply]
> However, I don't think you need to run AnyCable RPC as a server in Kamal's terms; it's more like a worker, a Sidekiq. I'm not sure if Kamal supports health checks for workers though.

My understanding of the `servers:` block in the config is that sidekiq would go there, too. I think services can be split into separate roles under that section, and they even mention workers as an example [in the docs](https://kamal-deploy.org/docs/configuration/servers/#roles). E.g., you would have your `web` service running alongside other roles (sidekiq, for one) in the same/other servers based on the `hosts` declared for each role. 

Regarding health checks for roles like sidekiq, I think it does support them with a `health-cmd` entry, at least I believe that's what is referred to as "Non proxy roles" in [this section](https://kamal-deploy.org/docs/upgrading/configuration-changes/#healthchecks).

However, I think anycable needs to have the proxy configuration, otherwise kamal won't be able to route traffic into anycable's instance running on the server at port 50051, right? E.g., when I declare the anycable-rpc role just as this:
```yml
anycable-rpc:
  hosts:
    - <%= ENV['WEBSOCKET_HOST'] %>
  cmd: bundle exec anycable
```

if I try to connect to my websocket host, let's say `wss://ws.my-app.example.com/cable` I get this in the kamal-proxy logs:
```
2024-11-07T15:12:00.188864516Z {"time":"2024-11-07T15:12:00.188668099Z","level":"INFO","msg":"http: TLS handshake error from xx.xx.xxx.xxx: unknown server name"}
```

which kinda makes sense because kamal proxy doesn't recognize it as a host.

**Reply by palkan** [reply]
> kamal won't be able to route traffic into anycable's instance running on the server at port 50051, right?

To be honest: I don't know. I'm not even sure kamal-proxy can proxy gRPC (raw HTTP2) traffic.

The `health-cmd` looks like what we need, then. You need to configure it to perform [gRPC health checks](https://docs.anycable.io/ruby/health_checking?id=grpc), for example, using https://github.com/grpc-ecosystem/grpc-health-probe.

**Reply by pjpires** [reply]
Hi @palkan,

I’ve been away for a few days, but after getting back, I spent some time on this issue and realized where I went wrong. 😅

The way kamal splits containers between "servers" and "accessories" confused me a bit. I was mistakenly trying to route traffic to the anyCable RPC container, which isn’t what we want. Instead, websocket traffic should go to the `anycable-go` container, which is defined as an "accessory" in my kamal setup. Since the proxy configuration only allows routing traffic to "servers", I was misled into thinking it should go to the RPC container.

Here’s what I actually need from kamal-proxy: besides routing HTTP traffic to the web server (as any other app), it should also route websocket traffic to the anycable-go container. Kamal doesn’t currently support this directly in the config file, but I found [this PR](https://github.com/basecamp/kamal/pull/981), which addresses a similar issue, hopefully it'll get merged. It also provided workarounds to make things work.

Here's what I did:

**1. Update the anycable RPC block in my config file**
I realised I was missing the publish option in the anycable-rpc block, which is necessary to forward traffic. Adding it passes the correct argument to the docker run command:
```yml
servers:
  # ... web, sidekiq, etc.

  anycable-rpc:
    hosts:
      - <%= ENV['WEBSOCKET_HOST'] %>
    cmd: bundle exec anycable
    options:
      publish: "127.0.0.1:50051:50051"
```
After this I deployed, but `anycable-go` can't still reach anycable RPC.

**2. Handle container name changes across deployments**
To allow `anycable-go` to communicate with RPC within the Docker network, I need the RPC container’s name. Services like `redis` or `postgres` (the "accessories") use stable names in the config, but for "servers" their name changes across deploys, as explained [here](https://github.com/basecamp/kamal/pull/981#issuecomment-2386769351). My workaround is to manually edit the `ANYCABLE_RPC_HOST` in the `anycable-go` block after deploying, using the updated container name:
```yml
anycable-go:
  # ... my previous config above
  env:
    clear:
      ANYCABLE_RPC_HOST: "my-app-anycable-rpc-staging-cf57da38850c10003e...:50051"
```
("-staging" comes from my deploy target, and the hash is the tag of the docker image used to run the container.)

After this change, I rebooted the `anycable-go` container to apply the changes:
```bash
kamal accessory reboot anycable-go
```
After the reboot, `anycable-go` was able to communicate with RPC on port 50051.

**3. Setup `kamal-proxy` routing**
Finally, I SSH into the host machine and use `kamal-proxy` to route traffic to the rebooted `anycable-go` container, e.g.:
```bash
docker exec kamal-proxy kamal-proxy deploy my-app-anycable-go-staging \
  --target my-app-anycable-go:8080 \
  --host ws.my-host.com \
  --health-check-path /health \
  --tls
```

After this, I was finally able to establish a websocket connection from the clients at `wss://ws.my-host.com/cable`. 🎉 

**Next steps**
As you can see, steps 2 and 3 are required after every deploy since they depend on the generated container name. Editing `deploy.yml` manually each time to update `ANYCABLE_RPC_HOST` is impractical. I found [this issue](https://github.com/basecamp/kamal/issues/1091), and plan to try a post-deploy hook to create a stable alias (e.g., `anycable-rpc`) and use that instead in my `deploy.yml`.

I'm not yet sure if this will fully address the issues in steps 2 and 3, but I’ll keep you updated on my progress.

Thanks for pointing me in the right direction!

**Reply by palkan** [reply]
Thanks a lot for the details!

Well, it looks like Kamal isn't meant (yet) for such setups. 

Have you considered Thruster, by the way? With it, you can pack all three components (Rails, RPC, AnyCable-Go) together. That's how most Kamal 1 users did, as far as I know.

**Reply by palkan** [reply]
Can't this trick be useful to have stable RPC name within the Docker network? https://x.com/skryukov_dev/status/1861117727924273512

**Reply by pjpires** [reply]
Hey @palkan! Totally, that was my conclusion too, coincidentally I also posted about it [here](https://github.com/basecamp/kamal/issues/1091#issuecomment-2498629542) yesterday. 😅 I was about to share my findings here, I think I've managed to tie up all the loose ends.

Here’s my current setup:

```yml
servers:
  web:
    - <%= ENV['HOST'] %>

  # sidekiq ...

  anycable-rpc:
    hosts:
      - <%= ENV['WEBSOCKET_HOST'] %>
    cmd: bundle exec anycable
    options:
      network-alias: my-app-anycable-rpc
      
# other settings

accessories:
  # db, redis ...
  anycable-go:
    image: anycable/anycable-go:1.5
    host: <%= ENV['WEBSOCKET_HOST'] %>
    env:
      clear:
        ANYCABLE_HOST: "0.0.0.0"
        ANYCABLE_PORT: 8080
        ANYCABLE_RPC_HOST: "my-app-anycable-rpc:50051"
        ANYCABLE_REDIS_URL: "redis://gooze-booze-api-redis:6379/0"
```

After discussing it with a friend, I realized that ports **don’t** need to be explicitly published to be accessible within the same Docker network. That was a helpful insight! I was able to remove the `publish:` option that had been causing issues with redeployment and container rotation.

I also added an alias to my deployment script that re-registers `anycable-go` with `kamal-proxy` (step 3 above), like this:

```yml
aliases:
  # predefined aliases, like console, shell, etc.

  add-anycable-go-to-proxy: |
    server exec docker exec kamal-proxy kamal-proxy deploy my-app-anycable-go-staging
    --target my-app-anycable-go:8080
    --host <%= ENV['WEBSOCKET_HOST'] %>
    --health-check-path /health
    --tls
```

Then, I call it from `.kamal/hooks/post-deploy` like so:

```sh
#!/bin/sh

kamal add-anycable-go-to-proxy
```

I’ve run through this a few times, and everything seems to be working fine when deploying from my development machine. Now, I’m tackling the process from CI, but I’m hopeful it will be a smaller challenge.

Thanks for your support!
