### ISSUE TITLE
AWS ECS - cannot deploy anycable

### ISSUE THREAD

**Issue by barth12** [anycable/anycable#107]
**Ruby version:* 2.6.6*

**`anycable` gem version:*1.0.1*

**`grpc` gem version:*1.30.0*

### What did you do?
I tried to deploy my app in AWS ECS. One container runs RoR app with GRPC server, the other container runs anycable-go server. This setup when run locally with docker-compose works fantastic. It is a challenge to make it work on AWS ECS though. 

### What did you expect to happen?
To run as smoothly as with docker-compose on my local environment. 

### What actually happened?
Anycable-go container cannot connect to GRPC server (running together with my ruby API). The log shows error:
`E 2020-07-27T17:57:02.530Z context=ws Websocket session initialization failed: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup API on 10.0.0.2:53: no such host"`

I believe this is a network issue (probably ENVs are incorrect or I am missing some).

My ENVs for actioncable-go container: 
```
ANYCABLE_HOST=0.0.0.0
ANYCABLE_RPC_HOST=API:50051 (where API is name for my API with GRPC server)
REDIS_URL=my redis endpoint (working for sure)
```

MY ENVs for api + gcpr container:
```
REDIS_URL=my redis endpoint (working for sure)
ANYCABLE_RPC_HOST=0.0.0.0:50051
CABLE_URL=ws://localhost:8080/cable
RAILS_ENV=production
```

I really appreciate any help cause I'm stucked. Thank you for you great work!

**Comment by Envek** [comment]
I don't know much about ECS but most probably you need to use `serviceName` of [service](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html) that creates task with grpc container instead of `API`. See [section about service discovery](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/common_use_cases.html#microservices_service_discovery) in ECS docs (grpc acts like microservice there).

It would be helpful if you also share your task and service definitions (you can hide long code blocks into [`<details>`](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287)).

---
```
lookup API on 10.0.0.2:53: no such host
```
This error literally means “I asked DNS server at 10.0.0.2:53 and they don't know any entity named `API`”

**Comment by barth12** [comment]
Thank you for the quick answer. Actually it looks like using container names like API is correct way to connect. What I was missing though is `links` section inside my container definition which lets two or more containers to communicate each other. Now I can connect to AWS ws endpoint and can connect to channel. What I am missing now is handling incoming messages in anycable-go. In logs I found only: `2020-07-30T09:31:16.559Z context=node sid=23f32f23ghhhtge5 Failed to handle incoming message '{` I believe it is the last step to make it working.

**Comment by palkan** [comment]
> handling incoming messages in anycable-go. I just don't get them. No logs I can find

Please, check that REDIS_URL used by **all Rails services** (RPC, web, background, whatever) and anycable-go is the same as when as the channel name used by AnyCable.

Try to run anycable-go with debugging mode on (`ANYCABLE_DEBUG=1`) and check for logs with the `context=hub` tag. There should be something like `Incoming message` when pub/sub is working correctly.

**Comment by multilot** [comment]
Thank you @palkan, My REDIS_URL is actually AWS ElastiCache Service so the URL is some long endpoint.
> as the channel name used by AnyCable

 I don't know where it should be then. My cable `anycable.yml` looks like this:
```
default: &default
  access_logs_disabled: false
  rpc_host: "127.0.0.1:50051"
  log_grpc: true
  broadcast_adapter: redis
  redis_channel: "__anycable__"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

```

I ran with debugging mode, I cannot see anything like `Incoming message`. 
It is weird cause I'm connected to GRPC and having pings, also I can broadcast message from a server but it won't reach client.

**Comment by barth12** [comment]
Thank you @palkan, My REDIS_URL is actually AWS ElastiCache Service so the URL is some long endpoint.

> as the channel name used by AnyCable

I don't know where it should be then. My cable anycable.yml looks like this:

```
default: &default
  access_logs_disabled: false
  rpc_host: "127.0.0.1:50051"
  log_grpc: true
  broadcast_adapter: redis
  redis_channel: "__anycable__"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```

I ran with debugging mode, I cannot see anything like `Incoming message`.
It is weird cause I'm connected to GRPC and having pings, also I can broadcast message from a server but it won't reach client.
